### PR TITLE
Add support for DeSEC DNS Hosting

### PR DESCRIPTION
**Pull request by nazar554**
https://desec.io/#!/en/product/dnshosting
https://desec.io/docs.html

TODO: support batch API

### CODE REVIEW

**Comment by rmbolger** [comment]
Thanks, @nazar554! This looks great. I'll try to run some tests soon and get it merged. Or did you want me to wait for the batch API stuff?

**Comment by rmbolger** [comment]
Or perhaps I won't be running tests quite yet. It seems the DNS hosting is still in beta. I signed up for beta access, but not sure when they'll get back to me.

**Comment by rmbolger** [comment]
Got my beta API key and I can test now. 

First question, can we remove the `DSTTL` required parameter and just hard code a default value for everything? I don't think Let's Encrypt actually adheres to TTLs for the purposes of validation and it would probably confuse a lot of end users.

Second, I think I ran into a bug. When creating a wildcard certificate that contains both the wildcard name, `*.example.com`, and the root name, `example.com`, the Add function seems to throw an error creating the second TXT record.

```
Invoke-RestMethod : {"__all__":["R rset with this Domain, Subname and Type already exists."]}
At C:\Users\user1\Documents\WindowsPowerShell\Modules\Posh-ACME\DnsPlugins\DeSEC.ps1:42 char:13
+             Invoke-RestMethod "https://desec.io/api/v1/domains/$($dom ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by nazar554** [comment]
Done, fixed second issue by escaping `...` with `%2e%2e%2e`. Also switched token to `[pscredential]` to make it work with .NET Core

**Comment by rmbolger** [comment]
Unfortunately, `[pscredential]` has the same problem as `[securestring]` on non-Windows OSes. What I've been doing is creating an alternate parameter set for "Insecure" versions of normally secure parameters. For instance, here's the param definition for the Aliyun plugin I just implemented:

```powershell
function Add-DnsTxtAliyun {
    [CmdletBinding(DefaultParameterSetName='Secure')]
    param(
        [Parameter(Mandatory,Position=0)]
        [string]$RecordName,
        [Parameter(Mandatory,Position=1)]
        [string]$TxtValue,
        [Parameter(Mandatory,Position=2)]
        [string]$AliKeyId,
        [Parameter(ParameterSetName='Secure',Mandatory,Position=3)]
        [securestring]$AliSecret,
        [Parameter(ParameterSetName='Insecure',Mandatory,Position=3)]
        [string]$AliSecretInsecure,
        [Parameter(ValueFromRemainingArguments)]
        $ExtraParams
    )
```

So you can either specify `-AliSecret` as a secure string or `-AliSecretInsecure` as a normal string. The `DefaultParameterSetName` is also important. If they forget to include either, it prompts for the one we'd prefer which is the secure one. And if they include both, it will also use the secure one. 

I'd suggest making changing `-DSToken` back to a securestring and adding a `-DSTokenInsecure` like the above example. Then since you end up using a normal string for the token anyway, the first thing you can do inside the function is something like this and then always use `$DSTokenInsecure` from that point forward.

```
# convert the secure token to a normal string
if ('Secure' -eq $PSCmdlet.ParameterSetName) {
    $DSTokenInsecure = (New-Object PSCredential ("user", $DSToken)).GetNetworkCredential().Password
}
```

**Comment by rmbolger** [comment]
Also, good catch on the `...` escaping.

**Comment by nazar554** [comment]
Done, both parameters work when using `pwsh.exe` on Windows

**Comment by rmbolger** [comment]
Awesome. Everything working on my end. I added a couple tiny comment-help fixes. This should go live in the next release.

**Pull request merged**
