### PR TITLE
Added Plugin for Registeram.com

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**
Registeram.com [provides an API here](https://my.registeram.com/index.php?/userapi/)

This plugin is my attempt at using LE wildcard certificates on Registeram.com via DNS validation.

I'm new to Powershell, your review is appreciated.

Regards.

_PS: It is not well documented how we may test a new plugin module. Elaboration on this would help.
Thanks._

### CODE REVIEW

**Review by CharlesOkwuagwu — COMMENTED** [review]
Added Help file: Registeram.md ... not Heel.md

**Comment by rmbolger** [comment]
Hi @CharlesOkwuagwu. Thanks for the submission! This will be the first Nigerian registrar I've worked with, congrats. I've ordered a new domain with them to test against and I'm just waiting for it to finish processing in order to start testing.

Regarding the plugin testing. There's a [Testing Plugins](https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Plugins/README.md#testing-plugins) section of the plugin development guide linked in the wiki. Were you looking for more than that? Or did I just not make it easy enough to find?

**Comment by CharlesOkwuagwu** [comment]
I'm not clear on how to proceed with the testing. I have read the Testing Plugins section. It does not clarify how we can link in our code to test

**Comment by rmbolger** [comment]
My apologies. I'll try and add some detail to it soon. Here's a bit more info that should help.

Your plugin file ultimately needs to be in the Plugins folder wherever your PowerShell session is loading the module from. After the module is imported, you should be able to run `Get-PAPlugin` and see yours in the list.

What I usually do is have the git repository cloned into a local folder like `C:\code\Posh-ACME`. There's a script in the root of that folder called `instdev.ps1`. When you run it, it copies the module files into the current user's PSModulePath, runs `Import-Module Posh-ACME -Force`, and lists the functions available in the module. So my working environment is basically a PowerShell window with the location set to `C:\code\Posh-ACME` and a VS Code editor open to the same folder (I prefer a separate PS window over the integrated console in VS Code). I modify code, save changes, switch to the PowerShell window and run `.\instdev.ps1` to re-copy and re-import the changed files. When I'm done, I execute the git commands necessary to commit my changes and push them up to Github.

**Comment by CharlesOkwuagwu** [comment]
> After the module is imported, you should be able to run `Get-PAPlugin` and see yours in the list.

I did not see my module in the list

**Comment by rmbolger** [comment]
Make sure you don't have additional copies of the module in other locations that might be taking precedence over the copy you're testing. You can double check by running `Get-Module -ListAvailable Posh-ACME`

**Comment by rmbolger** [comment]
Hey @CharlesOkwuagwu. I tried to start testing with the domain I just purchased, but I'm having trouble with the Setup section in the guide that suggests running `curl -k "https://www.registeram.com/ng/api/dns" -u username:password` to get the service ID and domain ID. I get an empty result that looks like this:

```json
{"service_ids":[],"zones":[]}
```

But if I use `https://www.registeram.com/ng/api/domain`, I see my domain in the results and its ID value which I can then use with `https://www.registeram.com/ng/api/domain/$ID/dns` to get the records in it. Do you know what the difference is between the "dns" and "domain" endpoints in the API?

Also, we don't really want to force users to Base64 encode their own credentials. I'd suggest changing the `[string]$RegisteramAuthHash` parameter to `[pscredential]$RegisteramCredential` and then doing the Base64 encoding for the Basic authentication header inside the function.

I'm hoping we can avoid the need for the `RegisteramServiceID` and `RegisteramDomainID` parameters as well and just discover those if necessary within the plugin code. I'll probably start working on this myself now that I have a domain to test against. But I'm curious if you see the same results as I do using the `domain` endpoint.

**Comment by CharlesOkwuagwu** [comment]
> Hey @CharlesOkwuagwu. I tried to start testing with the domain I just purchased, but I'm having trouble with the Setup section in the guide that suggests running `curl -k "https://www.registeram.com/ng/api/dns" -u username:password` to get the service ID and domain ID. I get an empty result that looks like this:
> 
> ```json
> {"service_ids":[],"zones":[]}
> ```
> 
> But if I use `https://www.registeram.com/ng/api/domain`, I see my domain in the results and its ID value which I can then use with `https://www.registeram.com/ng/api/domain/$ID/dns` to get the records in it. Do you know what the difference is between the "dns" and "domain" endpoints in the API?
> 
> Also, we don't really want to force users to Base64 encode their own credentials. I'd suggest changing the `[string]$RegisteramAuthHash` parameter to `[pscredential]$RegisteramCredential` and then doing the Base64 encoding for the Basic authentication header inside the function.
> 
> I'm hoping we can avoid the need for the `RegisteramServiceID` and `RegisteramDomainID` parameters as well and just discover those if necessary within the plugin code. I'll probably start working on this myself now that I have a domain to test against. But I'm curious if you see the same results as I do using the `domain` endpoint.

Remove the /ng/

If the domain you bought is not a /ng/ it might not work with /ng/

**Comment by rmbolger** [comment]
The domain I bought is in the .xyz TLD. But unfortunately, removing the `/ng` just gives me an HTTP 404 Not Found error.

**Comment by CharlesOkwuagwu** [comment]
> The domain I bought is in the .xyz TLD. But unfortunately, removing the `/ng` just gives me an HTTP 404 Not Found error.

Please give me a private email, I can send you access to try it out

**Comment by rmbolger** [comment]
I don't know what your email address is and it does not appear on your public Github profile.

**Comment by CharlesOkwuagwu** [comment]
> I don't know what your email address is and it does not appear on your public Github profile.

okwuagwucne@gmail.com

**Comment by CharlesOkwuagwu** [comment]
> I don't know what your email address is and it does not appear on your public Github profile.

I have sent you a DM on Twitter, with details.

Thanks for taking the time to review this.

**Comment by rmbolger** [comment]
Hey @CharlesOkwuagwu. Just wanted to let you know I haven't forgotten about this. I'm currently stuck waiting on a resolution for my support ticket with Registeram.

**Comment by CharlesOkwuagwu** [comment]
Thanks. I will find time to follow your directions and do the testing properly.

**Pull request closed without merging**
