### PR TITLE
NameSilo Plugin

### PR DESCRIPTION
**Pull request by rkone**
Add NameSilo as a supported DNS provider.

### CODE REVIEW

**Comment by rmbolger** [comment]
Hey @rkone. Thanks for the submission! I'm on vacation at the moment, so it may be a bit before I have a chance to review it. But just wanted to let you know I saw it and appreciate the effort.

**Comment by rmbolger** [comment]
Hi $rkone. I finally got around to reviewing this. I took the liberty of fixing a few bugs and adding support for specifying the API securely.

It seems to be working for me. But can you take a look and make sure I didn't break anything for your own usage?

**Comment by rkone** [comment]
Thanks for fixing it up @rmbolger !  I will try it hopefully tomorrow and get back to you.

**Comment by rkone** [comment]
@rmbolger  - your updates work fine for me!

**Comment by rmbolger** [comment]
Excellent. Merging now.

**Pull request merged**
