### PR TITLE
Add easyDNS plugin

### PR DESCRIPTION
**Pull request by abrysiuk**
This branch adds the EasyDNS plugin based on their BETA API. Readme includes link to documentation which has signup instructions.

### CODE REVIEW

**Comment by rmbolger** [comment]
Hey @abrysiuk. Thanks for this!. I had no idea EasyDNS didn't already have a released API.

It was probably just a typo, but can you rename the readme to use the `.md` extension?

I'm somewhat hesitant to merge this to master just yet since the API could potentially change before they go live. Do you mind if we wait a bit?

**Comment by abrysiuk** [comment]
A wait on it is fine - I was hesitant to even make the pull request ahead of time, but figured if they didn't change anything and it kept working for me, I'd forget to ever contribute the code.

**Comment by rmbolger** [comment]
Hey @abrysiuk. Any updates from EasyDNS? I'm considering just merging this even if it's still beta.

**Comment by abrysiuk** [comment]
They've updated their documentation to use Swagger (which is a little more helpful, but it's still kind of a mess). No other documentation announcing general availability.

http://sandbox.rest.easydns.net:3000/

The module still works, I continue to use it in production.

**Comment by rmbolger** [comment]
I added a `EDUseSandbox` switch which lets people optionally test against the sandbox environment. I also tweaked the readme and refactored the code a bit based on some lessons learned in previous plugins. I'm pretty sure everything should work the same, but EasyDNS hasn't responded to my API request so I don't have access to test on my own yet. Can you make sure I didn't break anything?

**Comment by rmbolger** [comment]
Nice. Thanks again for your time and patience. Hopefully EasyDNS will get off their butts eventually and make this officially supported.

**Pull request merged**
