### PR TITLE
Add support for DynECT DNS provider

### PR DESCRIPTION
**Pull request by jsgaard**

### CODE REVIEW

**Comment by rmbolger** [comment]
Hey @jsgaard. Thanks for the PR. I haven't had time to look at it just yet, but wanted to let you know I haven't forgotten about it.

**Comment by rmbolger** [comment]
Ok, this is going to be a tricky one because it doesn't look like I can sign up for an account anymore since the service is being sunset in favor of Oracle's cloud services. So I can't really run my own tests unless you're willing to temporarily share account credentials. Aside from actual testing, I do have a few suggestions though. 

First, I'd probably rename this from DynECT to something like DynManaged or DynManagedDNS. I realize the portal uses dynect.com as a domain name, but they call the service Dyn Managed DNS.

I'll try and add the rest of my suggestions inline in the code. Bear with me.

**Review by jsgaard — COMMENTED** [review]
Thanks for the taking the time to look through this.

I'll make a updated version (Can't give an estimate, got a few other things first) and hopefully answer a few of the questions you have. 

Unfortunate I'm unable to share credentials, since this is a company account.

**Comment by rmbolger** [comment]
Closing this in preparation for the 4.0 release and branch naming changes. Please re-submit if necessary after the 4.0 release.

**Pull request closed without merging**
