### PR TITLE
Add DNS plugin for DNS provider Domeneshop (https://domene.shop/)

### PR DESCRIPTION
**Pull request by ornulfn**
This branch adds DNS plugin for provider Domeneshop based on their BETA API. Readme includes link to documentation which has signup instructions.

### CODE REVIEW

**Comment by rmbolger** [comment]
Hey @ornulfn. Thanks for this! I noticed that the english version of their site goes to a different domain name, domainname.shop. Do you know whether the API URL (api.domeneshop.no) works against domains registered from the english version of the site?

**Comment by ornulfn** [comment]
Hi Ryan,

Yes, the API URL api.domeneshop.no work for all Domeneshop language versions

OBTW: Domeneshop have presence on GitHub - https://github.com/domeneshop

**Comment by rmbolger** [comment]
Awesome. I made a few tweaks to the readme and function help content. But this looks great. Thanks again.

**Comment by ornulfn** [comment]
Cool  - only happy to contribute to your project :)

**Comment by lahell** [comment]
Nice work, but so annoying that you beat me to it! Thought for sure I was the only one working on this:
https://github.com/lahell/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Domeneshop.ps1

**Comment by rmbolger** [comment]
Oh man, that's crazy! Thanks for the effort, regardless.

**Comment by lahell** [comment]
No problem. It was interesting to see how different our plugins were considering they end up doing the same thing.

**Pull request merged**
