### PR TITLE
Added plugin for core-networks.de

### PR DESCRIPTION
**Pull request by dwydler**
Hi @rmbolger,
as discussed (#381) here the Pull Request for my Plugin.
Your review is appreciated. I'm new in this area of development.

Regards,
Daniel

### CODE REVIEW

**Comment by rmbolger** [comment]
Looking great, @dwydler. I did a bit of code cleanup for better readability and debug logging as well as some help/guide tweaks. Can you make sure I didn't break anything? I don't have an account with Core Networks at the moment, so I'm doing this blind.

I'd also like to take a stab at moving the Commit functionality into the Save-DnsTxt function.

**Comment by dwydler** [comment]
> Looking great, @dwydler. I did a bit of code cleanup for better readability and debug logging as well as some help/guide tweaks.

Thanks for the improvements. 

> Can you make sure I didn't break anything?

Sure. I just had to change the type of a variable (see last commit). After the change the request of ssl certificates runs successfully.

> I'd also like to take a stab at moving the Commit functionality into the Save-DnsTxt function.
Like as discussed in the issue #381 i'm not a fan of global script variables.

**Comment by rmbolger** [comment]
Good catch on the types. I tweaked them to be a bit more specific though. Can you do me a favor and run a publish/unpublish test that mimics a DNS Alias being used like this? The `fake.tld` can be anything and doesn't have to exist. The `realzone.com` should be a zone you actually have on Core Networks but make sure it's the apex of the zone. If you already tested this, great! Just wanted to double check.

```powershell
$pArgs = @{ CoreNetworksCred = (Get-Credential) }
Publish-Challenge fake.tld (Get-PAAccount) faketoken CoreNetworks $pArgs -DnsAlias realzone.com
Unpublish-Challenge fake.tld (Get-PAAccount) faketoken CoreNetworks $pArgs -DnsAlias realzone.com
```

I know you had mentioned your dislike of global variables, but I may have to insist. The API documentation explicitly talks about not being suitable for high-frequency processing and I'd rather not abuse their service by calling commit for every single record added or removed. In the worst case, a certificate with 100 names would end up being over 400 calls between the adds, removes, and commits. But you cut that almost in half if you only commit per zone (depending on the number of unique zones).

I'd be willing to compromise and add a switch parameter like `CoreNetworksImmediateCommit` that would let users choose to commit during the Add call instead of waiting for the Save call. But I want the default functionality to be respectful of the provider.

**Comment by dwydler** [comment]
> Can you do me a favor and run a publish/unpublish test that mimics a DNS Alias being used like this?

Sure. Can you tell me what value the variable faketoken shoud be?

**Comment by dwydler** [comment]
> I know you had mentioned your dislike of global variables, but I may have to insist

Okay. With the last commit I adjusted the behavior accordingly.

**Comment by rmbolger** [comment]
> Sure. Can you tell me what value the variable faketoken shoud be?

The faketoken can literally be `faketoken` or really any string. I usually just use a single character like `a` because it's less to type.

**Comment by rmbolger** [comment]
I tweaked the Save stuff to only commit once per unique zone name and reverted some of the variables you had converted to script variables. Essentially, we only need a single script variable to keep track of the zones we've added records to. I think I need to document how the plugin Save flow works better. Notably, it gets passed the same set of plugin args sent by the user as Add/Remove do. The only thing it doesn't get is `$RecordName` and `$TxtValue`.

I'm also going to ponder about a better way for Add/Remove to pass constructed data needed for Save. But realistically, that's not something that can happen until 5.x.

In any case, give this last version a test and if everything works, I think it's good to merge.

**Comment by dwydler** [comment]
> The faketoken can literally be faketoken or really any string. I usually just use a single character like a because it's less to type. The TxtValue that actually gets saved to DNS will still look like gibberish because it's a base64 encoded hash of the key auth value.

The tests have been carried out again. It runs without any error. 
Below are my test commands. To make sure i done it right.
```
Publish-Challenge test.de (Get-PAAccount) a CoreNetworks $pArgs -DnsAlias "acme.domain.de"
Unpublish-Challenge test.de (Get-PAAccount) a CoreNetworks $pArgs -DnsAlias "acme.domain.de"
```

> I tweaked the Save stuff to only commit once per unique zone name and reverted some of the variables you had converted to script variables.

I review you changes and now it make sense. Thanks for the improvements.

> In any case, give this last version a test and if everything works, I think it's good to merge.

I ran the latest version successfully in my lab. Only the name of a variable was not correct (see last commit).

**Pull request merged**
