### PR TITLE
Ionos dns api v1.0

### PR DESCRIPTION
**Pull request by RLcyberTech**
I have written a plugin for the German Provider IONOS.
Would like to share my Work.
I'm new to GitHub, so hopefully I have done it correctly.

### CODE REVIEW

**Comment by rmbolger** [comment]
Hi @RLcyberTech, thanks for sharing! It might be a bit before I can review this, but I wanted to let you know I saw it.

**Comment by RLcyberTech** [comment]
Hi @rmbolger,
thank you for your Response.
Let me know if you need something to support your Testing.
Btw I'm planing to write another Plugin for another German provider.

**Comment by gitfvb** [comment]
I am also using IONOS and flew over the code which looked fine on the first sight. Let me know, if I can support testing here.

**Comment by rmbolger** [comment]
Found some time this weekend to grab a cheap domain and test this out. Great job overall. I hope you don't mind I renamed the parameters to `IONOSKeyPrefix` and `IONOSKeySecret`, did some code tidying, and added links to the english site as well in the guide. Things are working for me, but can you test my changes and make sure I didn't break anything before I merge this into main?

**Comment by rmbolger** [comment]
@RLcyberTech or @gitfvb, can either of you test my changes just to make sure I didn't break anything? Remember the updated param names I mentioned in the previous comment. It's working for me, but I always like to get at least one other person to sign off before I merge.

**Comment by gitfvb** [comment]
Hi @rmbolger, sorry, was ill for a few weeks, but I am back since yesterday.

I have just tested the new 4.17.0 with IONOS, created a new certificate which worked instantly like in the documentation. Great work  @RLcyberTech , @rmbolger ! This really is a cool project with a nice community.

**Pull request merged**
