### PR TITLE
Add support for different Azure cloud environments

### PR DESCRIPTION
**Pull request by InKahootz**
Fixes:  #293

### CODE REVIEW

**Comment by InKahootz** [comment]
Any feedback is welcome 😄

**Comment by rmbolger** [comment]
Hah, you beat me to the validationset fix by minutes. I made a small tweak to the usage guide so the AZEnvironment stuff is more prominent in the Using section.

**Comment by rmbolger** [comment]
In any case, everything is working for me. Stylistically, I have some minor hesitations with the AzureCloud class definition due to some legacy hassles I've had with PowerShell classes. I know things *should* work since everyone using the module should at least be on 5.1. But I'd probably have just defined those as plain old hashtable objects.

**Comment by InKahootz** [comment]
I refactored to hashtable so there wouldn't be any worry about classes. It's a drop in replacement so nothing big needed to be changed.

**Review by rmbolger — APPROVED** [review]

**Comment by rmbolger** [comment]
Love it. Merging.

**Comment by InKahootz** [comment]
Thanks for the merge and 3.20.0 release. Already using in our production pipeline and it works great!

**Pull request merged**
