### PR TITLE
Add Dreamhost DnsPlugin

### PR DESCRIPTION
**Pull request by jhendricks123**
Tested against my own Dreamhost account with success.

### CODE REVIEW

**Comment by rmbolger** [comment]
Hey @jhendricks123. Thanks for the plugin! Man, that DreamHost DNS api is rather...limited. I have just a few comments/requests before I merge this.

The security protocol tweaks you have in there shouldn’t be necessary. The module takes care of it conditionally on load. It’s conditional because the code isn’t compatible with PowerShell Core so it only needs to run in Desktop edition.

Can you add a basic usage guide similar to the others that exist? Include things like where to find the page to get your API key and example usage.

There are two common scenarios that most plugins handle that could use some additional error handling if I’m reading things correctly. Trying to add a record that already exists shouldn’t generate an error for the user. Trying to delete a record that doesn’t exist also shouldn’t generate an error. An easy way to test without needing to futz with actual cert stuff is just using `Publish-DNSChallenge` and `Unpublish-DNSChallenge` like this. 

```
$pArgs = @{DreamhostApiKey=‘xxxxxxxx’}
Publish-DNSChallenge example.com (Get-PAAccount) fake Dreamhost $pArgs
Publish-DNSChallenge example.com (Get-PAAccount) fake Dreamhost $pArgs
Unpublish-DNSChallenge example.com (Get-PAAccount) fake Dreamhost $pArgs
Unpublish-DNSChallenge example.com (Get-PAAccount) fake Dreamhost $pArgs
```

The first publish will add the record. The second one will fail from an api standpoint, but you should basically catch the “record exists” error and ignore it. The first unpublish will remove the record. The second will generate the “no record” error and you should just catch and ignore the same way.

**Comment by jhendricks123** [comment]
I didn't realize it shouldn't be considered an error for a DNS record to already exist - I'll swallow those errors. Should I write-error on any other error encountered?

I'll write up a guide in the next few days following the others as a template and send the updates your way :)

**Comment by rmbolger** [comment]
No worries. If we were making a more generic Dreamhost DNS API PowerShell wrapper, we probably would want to surface those errors. But for the purposes of a Posh-ACME plugin, we only care that the record we want to exist exists and the record we want to delete is gone. I'll usually catch those cases and just make a Write-Debug call that mentions the record already exists or was already deleted.

I should probably update the plugin dev guide to mention this as well.

**Comment by rmbolger** [comment]
Tangent question. Do you know if Dreamhost supports hosting DNS without actually transferring your domain to them. Like if someone wanted to keep their existing registrar but still have Dreamhost do the DNS (and presumably web) hosting, do they support that?

**Comment by jhendricks123** [comment]
Yep, all my domains are on GoDaddy and I only forward DNS over to Dreamhost.

**Comment by jhendricks123** [comment]
Let me know what you think - I've removed the SSL/TLS tweaks, and now only throw on errors besides "record already exists" or "record not found".

At first I handled the record exists/doesn't exist errors by looking for a matching record in the dns-list_records response, but realized that was wasteful and just swallowed the record_already_exists* and no_such_* responses.

**Comment by rmbolger** [comment]
Awesome. Thanks for the updates. Merging now.

**Pull request merged**
