### PR TITLE
Adds Reg.ru plugin

### PR DESCRIPTION
**Pull request by WiZaRd31337**
Adds support for DNS zones hosted at Reg.ru (https://reg.ru/)

### CODE REVIEW

**Comment by rmbolger** [comment]
A second new plugin? You are awesome, @WiZaRd31337. I'll probably hold off on reviewing this one until after we finish the Yandex one you submitted.

**Comment by WiZaRd31337** [comment]
Hi @rmbolger. Please, check new version.

**Comment by rmbolger** [comment]
Working on another plugin at the moment. But this one will be next.

**Comment by rmbolger** [comment]
I added URL escaping to the input bodies on the various requests so that special characters don't screw things up. I also slightly condensed the body string building. Overall, nice work though. 4 new plugins is amazing.

**Pull request merged**
