### PR TITLE
Company is called Simply.com, not Simply :)

### PR DESCRIPTION
**Pull request by tomsommer**

### CODE REVIEW

**Comment by rmbolger** [comment]
Thanks, @tomsommer. Always appreciative of corrections.

**Comment by rmbolger** [comment]
P.S. While I have you here, Tom. Does Simply.com have any plans for a v2 API that does not require putting the API Key directly in the endpoint URL? Having it in the URL means the value is likely getting leaked all over log files for things that use it.

**Comment by tomsommer** [comment]
@rmbolger We recognize the API is not optimal due to being built quickly and in another decade. At some point we will rewamp it :)

**Comment by rmbolger** [comment]
Totally understandable. Thanks.

**Pull request merged**
