### PR TITLE
Add plug-in for Ports Management DNS

### PR DESCRIPTION
**Pull request by wemmer**
[Ports Group](https://portsgroup.com/en) is a provider of, among other things, domain/DNS services based in Sweden.
The admin interface is available at: https://app.ports.management/#/dnsadmin

There is unfortunately no public easy sign-up, and in addition the production API requires IP whitelisting in Ports' firewall.
However, there is a demo environment that does not require IP whitelisting. 
Admin interface for that is available at https://demo.ports.management/, and API documentation is available at https://demo.ports.management/pmapi-doc/

I have developed this plugin to updated DNS records using their API. 
I've tried to follow all the tips and tricks in the plugin development guide docs, and as far as I can tell from my testing, it seems to be working.
The Publish-Challenge -> Unpublish-Challenge process works as expected for me.
My testing has been done on PowerShell version 5.1.19041.1682 and 7.2.5 on Windows 10.

Let me know if you have any questions, or need any help getting in touch with Ports to get credentials for the demo environment.

### CODE REVIEW

**Comment by rmbolger** [comment]
Sorry for the delay on responding to this, @wemmer. I totally the saw the notification come in and then got busy and forgot about it. Thanks for the contribution!. I'll try to review it soon.

**Review by rmbolger — APPROVED** [review]

**Comment by wemmer** [comment]
Sorry! Misclick on mobile. Did not intend to ask for further review.

**Comment by rmbolger** [comment]
This looks really good, @wemmer. It's probably not worth the hassle of me getting a demo account unless you or someone else runs into trouble using it.

Can you do me a favor and add references to the plugin in `Posh-ACME/Private/Import-PluginDetail.ps1` and `docs/Plugins/index.md`? Then we'll get it merged.

**Comment by wemmer** [comment]
@rmbolger the references have now been added.

**Comment by rmbolger** [comment]
Excellent. Merging now.

**Pull request merged**
